Repository YAPP-Github/Piece-Server, pull requests merged in 2024-12, with the labels that each got.

#4 feature : Login - Oauth 2.0 구조 설계 및 Kakao,Google 로그인 기능 구현
  api/src/main/java/org/yapp/domain/auth/api/LoginController.java
  api/src/main/java/org/yapp/domain/auth/application/jwt/JwtFilter.java
  api/src/main/java/org/yapp/domain/auth/application/jwt/JwtUtil.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/OauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/OauthProvider.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/OauthProviderResolver.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthProvider.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthProvider.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/auth/domain/enums/OauthType.java
  api/src/main/java/org/yapp/domain/auth/dto/request/OauthLoginRequest.java
  api/src/main/java/org/yapp/domain/auth/dto/response/OauthLoginResponse.java
  api/src/main/java/org/yapp/domain/auth/dto/response/OauthUserInfoResponse.java
  api/src/main/java/org/yapp/domain/user/dao/UserRepository.java
  api/src/main/java/org/yapp/domain/user/domain/User.java
  api/src/main/java/org/yapp/global/config/RestTemplateConfig.java
  api/src/main/java/org/yapp/global/config/SecurityConfig.java
  api/src/main/resources/application.yml
  api/src/test/java/org/yapp/domain/auth/application/jwt/JwtUtilTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/OauthProviderResolverTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClientTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthProviderTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthClientTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthProviderTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java
  build.gradle
Labels: 기능 구현, 설정 추가

#5 Feat: config - configure project
  api/build.gradle
  api/src/main/java/org/yapp/health/HealthCheckController.java
  build.gradle
  common/build.gradle
  common/src/main/java/org/yapp/config/SwaggerConfig.java
  common/src/main/java/org/yapp/error/GlobalExceptionHandler.java
  common/src/main/java/org/yapp/error/dto/CommonErrorCode.java
  common/src/main/java/org/yapp/error/dto/ErrorCode.java
  common/src/main/java/org/yapp/error/dto/ErrorResponse.java
  common/src/main/java/org/yapp/error/dto/SecurityErrorCode.java
  common/src/main/java/org/yapp/error/dto/UserErrorCode.java
  common/src/main/java/org/yapp/error/exception/ApplicationException.java
Labels: 기능 구현, 설정 추가

#8 Feature: 공통 응답 형식 추가 (#PC-31)
  api/src/main/java/org/yapp/domain/auth/api/LoginController.java
  api/src/main/java/org/yapp/global/common/dto/ApiResponse.java
Labels: 설정 추가

#9 [PC-177] 가치관 질문 리스트 조회 기능 구현
  api/src/main/java/org/yapp/domain/auth/api/LoginController.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/profile/api/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/api/response/ProfileResponse.java
  api/src/main/java/org/yapp/domain/profile/api/response/ProfileValueResponse.java
  api/src/main/java/org/yapp/domain/value/application/ValueItemService.java
  api/src/main/java/org/yapp/domain/value/dao/ValueItemRepository.java
  api/src/main/java/org/yapp/domain/value/presentation/ValueItemController.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/ValueItemResponse.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/ValueItemResponses.java
  api/src/main/java/org/yapp/global/config/SecurityConfig.java
  api/src/main/resources/init.sql
  common/src/main/java/org/yapp/domain/profile/ProfileValue.java
  common/src/main/java/org/yapp/domain/user/User.java
  common/src/main/java/org/yapp/domain/value/ValueItem.java
  common/src/main/java/org/yapp/util/ApiResponse.java
Labels: 기능 구현

#11 [PC-178] 프로필 가치관 생성 기능 로직
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueService.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValueRepository.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueResponse.java
  api/src/test/java/org/yapp/domain/auth/application/dummy/TestDataService.java
  api/src/test/java/org/yapp/domain/auth/application/profile/ProfileServiceTest.java
  api/src/test/java/org/yapp/domain/auth/application/profile/profileValue/ProfileValueServiceTest.java
  common/src/main/java/org/yapp/domain/profile/ProfileBasic.java
  common/src/main/java/org/yapp/domain/profile/ProfileValue.java
  common/src/main/java/org/yapp/domain/value/ValueItem.java
Labels: 기능 구현

#12 [PC-71] 프로필 가치관 업데이트 기능
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValueRepository.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePair.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValueUpdateRequest.java
  api/src/test/java/org/yapp/domain/auth/application/profile/ProfileServiceTest.java
  common/src/main/java/org/yapp/domain/profile/Profile.java
  common/src/main/java/org/yapp/domain/profile/ProfileValue.java
Labels: 기능 구현
