Repository YAPP-Github/Piece-Server, pull requests merged in 2025-03, with the labels that each got.

#69 [PC-684] FCM 토큰 관련 기능 구현
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/LogoutService.java
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/domain/user/dao/FcmTokenRepository.java
  api/src/main/java/org/yapp/domain/user/presentation/UserController.java
  api/src/main/java/org/yapp/domain/user/presentation/dto/request/FcmTokenSaveRequest.java
  core/auth/src/main/java/org/yapp/core/auth/jwt/JwtFilter.java
  core/domain/src/main/java/org/yapp/core/domain/fcm/FcmToken.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/AuthErrorCode.java
Labels: 기능 구현, 버그 수정

#71 [PC-698] ci/cd 개발, 운영 분리
  .github/workflows/cicd-api-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd.yml
  .github/workflows/pr-test.yml
  Dockerfile-admin
  Dockerfile-dev
  Dockerfile-prod
Labels: 기능 수정

#74 [PC-694] FCM 전송 로직 구현
  .gitignore
  admin/build.gradle
  admin/src/main/java/org/yapp/notification/application/AdminNotificationService.java
  admin/src/main/java/org/yapp/profile/application/AdminProfileService.java
  api/build.gradle
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/notification/application/ApiNotificationService.java
  api/src/main/java/org/yapp/domain/setting/application/SettingService.java
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  core/domain/src/main/java/org/yapp/core/domain/notification/NotificationHistory.java
  core/domain/src/main/java/org/yapp/core/domain/notification/enums/NotificationType.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/NotificationErrorCode.java
  core/notification/build.gradle
  core/notification/src/main/java/application/NotificationService.java
  core/notification/src/main/java/client/ApnClient.java
  core/notification/src/main/java/client/NotificationClient.java
  core/notification/src/main/java/org/yapp/core/notification/application/CommonNotificationService.java
  core/notification/src/main/java/org/yapp/core/notification/client/FcmClient.java
  core/notification/src/main/java/org/yapp/core/notification/client/NotificationClient.java
  core/notification/src/main/java/org/yapp/core/notification/dao/FcmTokenRepository.java
  core/notification/src/main/java/org/yapp/core/notification/dao/NotificationHistoryRepository.java
  core/notification/src/main/java/org/yapp/core/notification/enums/NotificationClientName.java
  core/notification/src/main/java/org/yapp/core/notification/provider/NotificationProvider.java
  infra/fcm/src/main/java/org/yapp/infra/fcm/application/FcmSendService.java
  infra/fcm/src/main/java/org/yapp/infra/fcm/config/FcmConfig.java
Labels: 기능 구현

#75 [PC-695] 알림 센터 기능 구현
  .github/workflows/cicd-api-prod.yml
  .github/workflows/cicd-dev.yml
  admin/src/main/java/org/yapp/notification/application/AdminNotificationService.java
  api/src/main/java/org/yapp/domain/match/batch/MatchScheduler.java
  api/src/main/java/org/yapp/domain/notification/application/ApiNotificationService.java
  api/src/main/java/org/yapp/domain/notification/application/NotificationHistoryService.java
  api/src/main/java/org/yapp/domain/notification/dto/request/NotificationRequest.java
  api/src/main/java/org/yapp/domain/notification/dto/response/NotificationHistoryResponse.java
  api/src/main/java/org/yapp/domain/notification/presentation/NotificationCenterController.java
  core/notification/src/main/java/org/yapp/core/notification/application/NotificationService.java
  core/notification/src/main/java/org/yapp/core/notification/dao/NotificationHistoryRepository.java
Labels: 기능 구현, 기능 수정

#78 [PC-722] 토큰 refresh 로직에서 refreshToken 만료시 에러 처리
  core/auth/src/main/java/org/yapp/core/auth/token/RefreshTokenService.java
Labels: 버그 수정

#77 [PC-718] 알림 읽음 체크 API 추가
  api/src/main/java/org/yapp/domain/notification/application/NotificationHistoryService.java
  api/src/main/java/org/yapp/domain/notification/dto/request/NotificationRequest.java
  api/src/main/java/org/yapp/domain/notification/presentation/NotificationCenterController.java
  core/domain/src/main/java/org/yapp/core/domain/notification/NotificationHistory.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/NotificationErrorCode.java
Labels: 기능 구현, 기능 수정

#76 [PC-719] 알람 정보 dateTime 추가
  api/src/main/java/org/yapp/domain/notification/application/NotificationHistoryService.java
  api/src/main/java/org/yapp/domain/notification/dto/request/NotificationRequest.java
  api/src/main/java/org/yapp/domain/notification/dto/response/NotificationHistoryResponse.java
  api/src/main/java/org/yapp/domain/notification/presentation/NotificationCenterController.java
  core/domain/src/main/java/org/yapp/core/domain/notification/NotificationHistory.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/NotificationErrorCode.java
Labels: 기능 수정

#80 [PC-710] 가치관 Pick / Talk 원본 질문 식별값 데이터 전달
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileBasicUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValuePickResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValuePickResponses.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponse.java
Labels: 기능 구현

#82 [PC-791] 연락처 차단 동기화 시간 형식 변경
  api/src/main/java/org/yapp/domain/setting/dto/response/BlockContactSyncTimeResponse.java
Labels: 기능 수정

#81 [PC-756] 병렬처리와 BloomFilter를 이용한 매칭 로직 최적화
  api/src/main/java/org/yapp/domain/block/application/BlockContactService.java
  api/src/main/java/org/yapp/domain/block/application/BloomBlockRepairService.java
  api/src/main/java/org/yapp/domain/block/application/BloomBlockService.java
  api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
  api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java
  api/src/main/java/org/yapp/domain/block/presentation/BlockRepairController.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/GreedyMatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/PreferenceBasedMatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/blocker/AcquaintanceBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/application/blocker/BloomFilterBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/application/matcher/PreferenceBasedMatcher.java
  api/src/main/java/org/yapp/domain/match/dao/MatchInfoRepository.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValuePickService.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValuePickRepository.java
  docker-compose.yml
  infra/redis/src/main/java/org/yapp/infra/redis/application/RedisService.java
  infra/redis/src/main/java/org/yapp/infra/redis/config/RedisConfig.java
Labels: 기능 구현, 설정 추가, 기능 수정
