Repository YAPP-Github/Piece-Server, pull requests merged in 2025-01, with the labels that each got.

#15 [PC-194] 이미지 등록 API
  api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/resources/application.yml
  build.gradle
  common/src/main/java/org/yapp/config/S3Config.java
  common/src/main/java/org/yapp/infra/s3/application/S3Service.java
Labels: 기능 구현

#14 [PC-106] SMS 인증 시스템 구현
  api/src/main/java/org/yapp/domain/auth/application/authorization/AuthCodeGenerator.java
  api/src/main/java/org/yapp/domain/auth/application/authorization/SmsAuthService.java
  api/src/main/java/org/yapp/domain/user/domain/User.java
  api/src/main/java/org/yapp/global/application/SmsSenderService.java
  api/src/test/java/org/yapp/domain/auth/application/authorization/AuthCodeGeneratorTest.java
  api/src/test/java/org/yapp/domain/auth/application/authorization/SmsAuthServiceTest.java
  api/src/test/java/org/yapp/domain/integration/SmsAuthTest.java
  api/src/test/java/org/yapp/global/application/SmsSenderServiceTest.java
  build.gradle
Labels: 기능 구현, 설정 추가

#17 [PC-214] 회원가입 절차에 SMS 인증번호 검증 로직 추가
  api/src/main/java/org/yapp/domain/auth/application/authorization/SmsAuthService.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java
  api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/enums/RoleStatus.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/request/SmsAuthRequest.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/request/SmsAuthVerifyRequest.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/response/OauthLoginResponse.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/global/application/RedisService.java
  api/src/main/java/org/yapp/global/config/SecurityConfig.java
  api/src/test/java/org/yapp/domain/auth/application/authorization/SmsAuthServiceTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java
  build.gradle
  common/src/main/java/org/yapp/application/AuthenticationService.java
  common/src/main/java/org/yapp/config/RedisConfig.java
  common/src/main/java/org/yapp/domain/user/User.java
  common/src/main/java/org/yapp/error/code/auth/SmsAuthErrorCode.java
  common/src/main/java/org/yapp/infra/s3/application/S3Service.java
Labels: 기능 구현, 설정 추가

#16 [PC-197] 약관 기능
  api/src/main/java/org/yapp/domain/term/applicatoin/TermService.java
  api/src/main/java/org/yapp/domain/term/applicatoin/TermUseCase.java
  api/src/main/java/org/yapp/domain/term/applicatoin/dto/SignupTermsDto.java
  api/src/main/java/org/yapp/domain/term/dao/TermAgreementRepository.java
  api/src/main/java/org/yapp/domain/term/dao/TermRepository.java
  api/src/main/java/org/yapp/domain/term/presentation/TermController.java
  api/src/main/java/org/yapp/domain/term/presentation/dto/response/TermResponse.java
  api/src/main/java/org/yapp/domain/term/presentation/dto/response/TermResponses.java
  api/src/main/resources/init.sql
  api/src/test/java/org/yapp/domain/auth/application/term/TermUseCaseTest.java
  common/src/main/java/org/yapp/domain/term/Term.java
  common/src/main/java/org/yapp/domain/term/TermAgreement.java
  common/src/main/java/org/yapp/error/dto/TermErrorCode.java
Labels: 기능 구현

#18 [PC-290] 회원가입 로직 점검
  api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java
  api/src/main/java/org/yapp/domain/term/applicatoin/TermUseCase.java
  api/src/main/java/org/yapp/domain/term/presentation/TermController.java
  api/src/main/java/org/yapp/domain/term/presentation/dto/request/TermAgreementRequest.java
  api/src/main/java/org/yapp/domain/term/presentation/dto/response/TermResponse.java
  api/src/main/resources/application.yml
  common/src/main/java/org/yapp/domain/term/Term.java
  common/src/main/java/org/yapp/error/dto/TermErrorCode.java
  common/src/main/java/org/yapp/util/CommonResponse.java
  docker-compose.yml
Labels: 기능 수정

#20 [PC-293] 차단 핸드폰 번호 추가 및 조회
  api/src/main/java/org/yapp/domain/block/application/BlockService.java
  api/src/main/java/org/yapp/domain/block/application/dto/BlockCreateDto.java
  api/src/main/java/org/yapp/domain/block/dao/BlockRepository.java
  api/src/main/java/org/yapp/domain/block/presentation/BlockController.java
  api/src/main/java/org/yapp/domain/block/presentation/dto/request/BlockPhoneNumbersRequest.java
  api/src/main/java/org/yapp/domain/block/presentation/dto/response/BlockResponse.java
  api/src/main/java/org/yapp/domain/block/presentation/dto/response/UserBlockResponses.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/term/presentation/TermController.java
  api/src/main/java/org/yapp/domain/value/presentation/ValueItemController.java
  api/src/main/resources/init.sql
  common/src/main/java/org/yapp/config/JpaConfig.java
  common/src/main/java/org/yapp/domain/BaseEntity.java
  common/src/main/java/org/yapp/domain/block/Block.java
  common/src/main/java/org/yapp/domain/user/User.java
  common/src/main/java/org/yapp/util/CommonResponse.java
Labels: 기능 구현

#21 [PC-297] 프로필 도메인 리팩토링
  api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValuePickService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkService.java
  api/src/main/java/org/yapp/domain/profile/application/dto/ProfileCreateDto.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValuePickRepository.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValueRepository.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValueTalkRepository.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePair.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePickCreateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePickPair.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePickUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValueTalkCreateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValueUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValuePickResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponse.java
  api/src/main/java/org/yapp/domain/term/applicatoin/TermUseCase.java
  api/src/main/java/org/yapp/domain/term/applicatoin/dto/SignupTermsDto.java
  api/src/main/java/org/yapp/domain/value/application/ValueItemService.java
  api/src/main/java/org/yapp/domain/value/application/ValuePickService.java
  api/src/main/java/org/yapp/domain/value/application/ValueTalkService.java
  api/src/main/java/org/yapp/domain/value/dao/ValueItemRepository.java
  api/src/main/java/org/yapp/domain/value/dao/ValuePickRepository.java
  api/src/main/java/org/yapp/domain/value/dao/ValueTalkRepository.java
  api/src/main/java/org/yapp/domain/value/presentation/ValueItemController.java
  api/src/main/java/org/yapp/domain/value/presentation/ValuePickController.java
  api/src/main/java/org/yapp/domain/value/presentation/ValueTalkController.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/ValueItemResponse.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/ValueItemResponses.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/response/ValuePickAnswerResponse.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/response/ValuePickResponse.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/response/ValuePickResponses.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/response/ValueTalkResponse.java
  api/src/main/java/org/yapp/domain/value/presentation/dto/response/ValueTalkResponses.java
  api/src/main/resources/init.sql
  api/src/test/java/org/yapp/domain/auth/application/dummy/TestDataService.java
  api/src/test/java/org/yapp/domain/auth/application/profile/ProfileServiceTest.java
  api/src/test/java/org/yapp/domain/auth/application/profile/profileValue/ProfileValuePickServiceTest.java
  api/src/test/java/org/yapp/domain/auth/application/profile/profileValue/ProfileValueServiceTest.java
  common/src/main/java/org/yapp/domain/profile/Profile.java
  common/src/main/java/org/yapp/domain/profile/ProfileBasic.java
  common/src/main/java/org/yapp/domain/profile/ProfileBio.java
  common/src/main/java/org/yapp/domain/profile/ProfileValuePick.java
  common/src/main/java/org/yapp/domain/profile/ProfileValueTalk.java
  common/src/main/java/org/yapp/domain/user/User.java
  common/src/main/java/org/yapp/domain/value/ValueItem.java
  common/src/main/java/org/yapp/domain/value/ValuePick.java
  common/src/main/java/org/yapp/domain/value/ValueTalk.java
Labels: 버그 수정, 기능 수정

#22 [PC-267] 매칭 기능 구조 설계 및 일부 구현
  api/src/main/java/org/yapp/ApiApplication.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/PreferenceBasedMatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/blocker/AcquaintanceBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/application/blocker/Blocker.java
  api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/application/blocker/PreviousMatchBlocker.java
  api/src/main/java/org/yapp/domain/match/application/matcher/CoupleMatcher.java
  api/src/main/java/org/yapp/domain/match/application/matcher/PreferenceBasedMatcher.java
  api/src/main/java/org/yapp/domain/match/batch/MatchScheduler.java
  api/src/main/java/org/yapp/domain/match/dao/MatchInfoRepository.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValuePickService.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileRepository.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValuePickRepository.java
  api/src/main/java/org/yapp/domain/profile/enums/Location.java
  common/src/main/java/org/yapp/domain/match/MatchInfo.java
  common/src/main/java/org/yapp/domain/user/User.java
  common/src/main/java/org/yapp/error/dto/MatchErrorCode.java
Labels: 기능 구현, 설정 추가

#23 [PC-361] 프로필 업데이트 로직 분리
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/enums/RoleStatus.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/PreferenceBasedMatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValuePickService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkService.java
  api/src/main/java/org/yapp/domain/profile/application/util/DateUtils.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileRepository.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValuePickRepository.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileValueTalkRepository.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileBasicUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePickPair.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValuePickUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileValueTalkUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValuePickResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValuePickResponses.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponses.java
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/domain/value/application/ValueTalkService.java
  api/src/main/java/org/yapp/domain/value/presentation/ValueTalkController.java
  build.gradle
  common/src/main/java/org/yapp/domain/profile/ProfileBasic.java
  common/src/main/java/org/yapp/domain/profile/ProfileValueTalk.java
Labels: 기능 구현, 기능 수정

#32 [PC-273] 매칭 상대 차단 기능 구현
  api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
  api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java
  api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  common/src/main/java/org/yapp/domain/block/DirectBlock.java
Labels: 기능 구현

#31 [PC-271] 매칭 수락 기능 및 연락처 조회 기능 구현
  api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
  api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/ContactResponse.java
  common/src/main/java/org/yapp/domain/block/DirectBlock.java
  common/src/main/java/org/yapp/domain/match/MatchInfo.java
  common/src/main/java/org/yapp/error/dto/MatchErrorCode.java
Labels: 기능 구현

#30 [PC-270] 매칭 조각 확인 기능 구현
  api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
  api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/ContactResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/ImageUrlResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchProfileBasicResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickInnerResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValueTalkInnerResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValueTalkResponse.java
  common/src/main/java/org/yapp/domain/block/DirectBlock.java
  common/src/main/java/org/yapp/domain/match/MatchInfo.java
  common/src/main/java/org/yapp/domain/match/enums/MatchStatus.java
  common/src/main/java/org/yapp/error/dto/MatchErrorCode.java
Labels: 기능 구현

#29 [PC-268] Greedy 매칭 알고리즘 구현
  .github/workflows/cicd.yml
  .github/workflows/pr-test.yml
  Dockerfile-admin
  Dockerfile-dev
  api/src/main/java/org/yapp/domain/block/application/BlockService.java
  api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
  api/src/main/java/org/yapp/domain/block/dao/BlockRepository.java
  api/src/main/java/org/yapp/domain/block/dao/DirectBlockRepository.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/GreedyMatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/MatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/PreferenceBasedMatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/blocker/AcquaintanceBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/application/blocker/DirectBlockBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/application/blocker/PreviousMatchBlocker.java
  api/src/main/java/org/yapp/domain/match/application/matcher/PreferenceBasedMatcher.java
  api/src/main/java/org/yapp/domain/match/batch/MatchScheduler.java
  api/src/main/java/org/yapp/domain/match/dao/MatchInfoRepository.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/ContactResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/ImageUrlResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchProfileBasicResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickInnerResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValueTalkInnerResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValueTalkResponse.java
  api/src/main/resources/init.sql
  api/src/test/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthProviderTest.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java
  api/src/test/java/org/yapp/domain/integration/SmsAuthTest.java
  build.gradle
  common/src/main/java/org/yapp/domain/block/DirectBlock.java
  common/src/main/java/org/yapp/domain/match/MatchInfo.java
  common/src/main/java/org/yapp/domain/match/enums/MatchStatus.java
  common/src/main/java/org/yapp/error/dto/MatchErrorCode.java
  docker-compose.yml
Labels: 기능 구현

#35 [PC-440] 머지 뒤 생긴 에러들 수정
  .github/workflows/cicd.yml
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/block/application/BlockContactService.java
  api/src/main/java/org/yapp/domain/block/dao/BlockContactRepository.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/GreedyMatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/blocker/AcquaintanceBasedBlocker.java
  api/src/test/java/org/yapp/domain/auth/application/dummy/TestDataService.java
  build.gradle
  common/build.gradle
  common/domain/src/main/java/org/yapp/domain/block/DirectBlock.java
  common/domain/src/main/java/org/yapp/domain/match/MatchInfo.java
  common/domain/src/main/java/org/yapp/domain/match/enums/MatchStatus.java
  common/src/main/java/org/yapp/domain/match/MatchInfo.java
Labels: 버그 수정

#24 [PC-333] 깃허브 액션 CICD 설정 with docker
  .github/workflows/cicd.yml
  Dockerfile-prod
Labels: 기능 구현

#36 [PC-272] 유저 신고 기능 구현
  api/src/main/java/org/yapp/domain/report/application/ReportService.java
  api/src/main/java/org/yapp/domain/report/controller/ReportController.java
  api/src/main/java/org/yapp/domain/report/dao/ReportRepository.java
  api/src/main/java/org/yapp/domain/report/dto/request/UserReportRequest.java
  common/src/main/java/org/yapp/error/dto/ReportErrorCode.java
Labels: 기능 구현
