Repository YAPP-Github/Piece-Server, pull requests merged in 2025-05, with the labels that each got.

#97 [PC-900] 유저 정지 기능 구현
  admin/build.gradle
  admin/src/main/java/org/yapp/ban/application/BanModifyingService.java
  admin/src/main/java/org/yapp/ban/application/BanService.java
  admin/src/main/java/org/yapp/ban/presentation/BanController.java
  admin/src/main/java/org/yapp/ban/presentation/dto/request/UserBanRequest.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java
  api/src/main/java/org/yapp/domain/user/application/BanCheckingService.java
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/global/config/InterceptorConfig.java
  api/src/main/java/org/yapp/global/interceptor/BanCheckingInterceptor.java
  core/auth/src/main/java/org/yapp/core/auth/dao/BannedUserPhoneNumberRepository.java
  core/domain/src/main/java/org/yapp/core/domain/user/BannedUserPhoneNumber.java
  core/domain/src/main/java/org/yapp/core/domain/user/RoleStatus.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/AuthErrorCode.java
  infra/redis/src/main/java/org/yapp/infra/redis/application/RedisService.java
Labels: 기능 구현

#98 [PC-908] 정지 유저 재가입 방지로직에서 에러처리
  api/src/main/java/org/yapp/domain/user/application/UserService.java
Labels: 기능 수정

#96 [PC-882] 가치관 톡 수정시 디스코드 알림
  admin/src/main/resources/application.yml
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValuePickService.java
  api/src/main/java/org/yapp/domain/profile/application/event/ProfileEventDiscordListener.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/resources/application.yml
  core/domain/src/main/java/org/yapp/core/domain/profile/event/ProfileCreatedEvent.java
  core/domain/src/main/java/org/yapp/core/domain/profile/event/ProfileEvent.java
  core/domain/src/main/java/org/yapp/core/domain/profile/event/ProfileImageUpdatedEvent.java
  core/domain/src/main/java/org/yapp/core/domain/profile/event/ProfileRenewedEvent.java
  core/domain/src/main/java/org/yapp/core/domain/profile/event/ProfileValueTalkUpdatedEvent.java
  gradlew
  infra/discord/src/main/java/org/yapp/infra/discord/DiscordMessageFactory.java
Labels: 기능 구현, 리팩토링

#100 [PC-921] AuthCodeGenerator 에서 String을 반환하도록 변경
  api/src/main/java/org/yapp/domain/auth/application/authorization/AuthCodeGenerator.java
  api/src/main/java/org/yapp/domain/auth/application/authorization/SmsAuthService.java
  api/src/test/java/org/yapp/domain/auth/application/authorization/AuthCodeGeneratorTest.java
  api/src/test/java/org/yapp/domain/auth/application/authorization/SmsAuthServiceTest.java
Labels: 리팩토링

#101 [PC-876] 수정된 프로필 이미지 심사
  admin/src/main/java/org/yapp/notification/application/AdminNotificationService.java
  admin/src/main/java/org/yapp/profile/application/AdminProfileImageService.java
  admin/src/main/java/org/yapp/profile/application/AdminProfileService.java
  admin/src/main/java/org/yapp/profile/dao/ProfileImageRepository.java
  admin/src/main/java/org/yapp/profile/presentation/ProfileImagesController.java
  admin/src/main/java/org/yapp/profile/presentation/request/UpdateProfileImageStatusRequest.java
  admin/src/main/java/org/yapp/user/application/UserService.java
  admin/src/main/java/org/yapp/user/presentation/UserController.java
  admin/src/main/java/org/yapp/user/presentation/request/UpdateProfileStatusRequest.java
  admin/src/main/java/org/yapp/user/presentation/response/UserProfileImageDetailResponse.java
  admin/src/main/java/org/yapp/user/presentation/response/UserProfileImageResponse.java
  admin/src/main/java/org/yapp/user/presentation/response/UserProfileValidationResponse.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/application/dto/ProfileImageDto.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileImageRepository.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicResponse.java
  api/src/main/resources/application.yml
  core/domain/src/main/java/org/yapp/core/domain/notification/enums/NotificationType.java
  core/domain/src/main/java/org/yapp/core/domain/profile/Profile.java
  core/domain/src/main/java/org/yapp/core/domain/profile/ProfileBasic.java
  core/domain/src/main/java/org/yapp/core/domain/profile/ProfileImage.java
  core/domain/src/main/java/org/yapp/core/domain/profile/ProfileImageStatus.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/ProfileImageErrorCode.java
  gradlew
Labels: 기능 구현, 기능 수정, 리팩토링

#102 [PC-895] 매칭 로직 리팩토링
  api/src/main/java/org/yapp/domain/block/blocker/AcquaintanceBasedBlocker.java
  api/src/main/java/org/yapp/domain/block/blocker/BloomFilterBasedBlocker.java
  api/src/main/java/org/yapp/domain/block/blocker/DirectBlockBasedBlocker.java
  api/src/main/java/org/yapp/domain/block/blocker/IdBasedBlocker.java
  api/src/main/java/org/yapp/domain/block/blocker/PreviousMatchIdBasedBlocker.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/GreedyMatchAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/MatchAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/MatchingAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/block/MatchBlocker.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/preference/PreferenceCalculatingPolicy.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/preference/SqlCalculatingPolicy.java
  api/src/main/java/org/yapp/domain/match/application/blocker/Blocker.java
  api/src/main/java/org/yapp/domain/match/application/match/DailyMatch.java
  api/src/main/java/org/yapp/domain/match/application/match/LocationAndPreferenceBasedDailyMatch.java
  api/src/main/java/org/yapp/domain/match/application/matcher/CoupleMatcher.java
  api/src/main/java/org/yapp/domain/match/batch/MatchScheduler.java
Labels: 리팩토링

#107 [PC-961] google Oauth 설정에 ios 클라이언트 추가
  api/src/main/java/org/yapp/global/config/GoogleOauthConfig.java
Labels: 설정 추가

#108 [PC-929] 어드민 개선 사항
  admin/src/main/java/org/yapp/report/application/ReportService.java
  admin/src/main/java/org/yapp/report/presentation/response/ReportDetailResponse.java
  admin/src/main/java/org/yapp/report/presentation/response/ReportUserResponse.java
  admin/src/main/java/org/yapp/user/application/UserService.java
  admin/src/main/java/org/yapp/user/presentation/response/UserProfileDetailResponses.java
  admin/src/main/java/org/yapp/user/presentation/response/UserProfileValidationResponse.java
  api/src/main/java/org/yapp/domain/report/application/ReportService.java
  api/src/main/java/org/yapp/domain/report/application/event/ReportEventDiscordListener.java
  core/domain/src/main/java/org/yapp/core/domain/report/event/ReportEvent.java
  infra/discord/src/main/java/org/yapp/infra/discord/DiscordMessageFactory.java
Labels: 기능 구현, 기능 수정
