Repository YAPP-Github/Piece-Server, pull requests merged in 2025-02, with the labels that each got.

#39 [PC-000] 프로필 연락처 타입 수정
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/ContactResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileBasicUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicResponse.java
  core/build.gradle
  core/domain/src/main/java/org/yapp/core/domain/profile/ContactType.java
  core/domain/src/main/java/org/yapp/core/domain/profile/Profile.java
  core/domain/src/main/java/org/yapp/core/domain/profile/ProfileBasic.java
  infra/build.gradle
Labels: 리팩토링

#38 [PC-443] 매치 프로필 누락 요소 및 통일되지 않은 변수명 수정
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchProfileBasicResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValueTalkResponse.java
Labels: 버그 수정

#42 [PC-518] 프로필 이미지 등록 설정 수정
  api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/ProfileErrorCode.java
Labels: 기능 구현

#41 [PC-478] SSE Flux 구현
  api/build.gradle
  api/src/main/java/org/yapp/domain/profile/application/ProfileImageService.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/global/config/SecurityConfig.java
  api/src/main/java/org/yapp/sse/presentation/SseController.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/ProfileErrorCode.java
  core/sse/build.gradle
  core/sse/src/main/java/org/yapp/core/sse/FluxSsePersonalService.java
  core/sse/src/main/java/org/yapp/core/sse/SsePersonalService.java
  core/sse/src/main/java/org/yapp/core/sse/dto/EventType.java
  core/sse/src/main/java/org/yapp/core/sse/dto/SsePayload.java
  settings.gradle
Labels: 기능 구현

#43 [PC-477] 리프레시 토큰 및 헬스체크 기능 추가
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/request/RefreshTokenRequest.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/request/TokenHealthCheckRequest.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/response/RefreshedTokensResponse.java
  core/auth/build.gradle
  core/auth/src/main/java/org/yapp/core/auth/dao/RefreshTokenRepository.java
  core/auth/src/main/java/org/yapp/core/auth/dto/RefreshedTokens.java
  core/auth/src/main/java/org/yapp/core/auth/token/RefreshTokenService.java
  core/auth/src/main/java/org/yapp/core/auth/token/TokenHealthCheckService.java
  core/domain/src/main/java/org/yapp/core/domain/auth/RefreshToken.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/SecurityErrorCode.java
Labels: 기능 구현

#40 [PC-414] FCM 푸시 모듈 구현
  core/domain/src/main/java/org/yapp/core/domain/fcm/FcmToken.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/NotificationErrorCode.java
  core/notification/build.gradle
  core/notification/src/main/java/application/NotificationService.java
  core/notification/src/main/java/client/ApnClient.java
  core/notification/src/main/java/client/FcmClient.java
  core/notification/src/main/java/client/NotificationClient.java
  core/notification/src/main/java/enums/NotificationClientName.java
  core/notification/src/main/java/provider/NotificationProvider.java
  infra/fcm/build.gradle
  infra/fcm/src/main/java/application/FcmSendService.java
  infra/fcm/src/main/java/config/FcmConfig.java
  settings.gradle
Labels: 기능 구현

#46 [PC-546] 프로필 톡 필드 변경
  api/src/main/java/org/yapp/domain/value/presentation/dto/response/ValueTalkResponse.java
  api/src/main/resources/init.sql
  core/domain/src/main/java/org/yapp/core/domain/value/ValueTalk.java
Labels: 기능 수정

#45 [PC-474] AI 프로필 요약 기능
  api/build.gradle
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkService.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkSummaryService.java
  api/src/main/java/org/yapp/domain/profile/application/util/NickNameGenerator.java
  api/src/main/java/org/yapp/domain/profile/application/util/NicknameGenerator.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/sse/presentation/response/ProfileValueTalkSummaryResponse.java
  api/src/main/resources/application.yml
  core/exception/src/main/java/org/yapp/core/exception/error/code/ProfileValueTalkErrorCode.java
  core/sse/src/main/java/org/yapp/core/sse/dto/EventType.java
  infra/ai/build.gradle
  infra/ai/src/main/java/org/yapp/infra/ai/application/ClovaChatSummarizationService.java
  infra/ai/src/main/java/org/yapp/infra/ai/application/SummarizationService.java
  infra/ai/src/main/java/org/yapp/infra/ai/config/WebClientConfig.java
  settings.gradle
Labels: 기능 구현

#47 [PC-547] 연락처 데이터 리스트 전달
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileBasicUpdateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileCreateRequest.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ContactResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ContactResponses.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/validation/ContactTypeValidator.java
  api/src/main/java/org/yapp/domain/profile/presentation/validation/ValidContactType.java
Labels: 기능 구현, 기능 수정

#48 [PC-548] 자신의 프로필 기본정보 미리보기
  admin/src/main/java/org/yapp/block/application/UserBlockService.java
  admin/src/main/java/org/yapp/block/dao/DirectBlockRepository.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/ImageUrlResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileBasicPreviewResponse.java
  core/domain/src/main/java/org/yapp/core/domain/block/DirectBlock.java
  core/domain/src/main/java/org/yapp/core/domain/block/UserBlock.java
Labels: 기능 구현, 기능 수정

#51 [PC-545] 프로필 생성시 AI 요약
  api/src/main/java/org/yapp/domain/auth/presentation/SmsAuthController.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkSummaryService.java
  api/src/main/java/org/yapp/domain/profile/presentation/ProfileController.java
  api/src/main/java/org/yapp/domain/profile/presentation/request/ProfileTalkSummaryUpdateRequest.java
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/sse/presentation/SseController.java
  core/sse/src/main/java/org/yapp/core/sse/FluxSsePersonalService.java
  infra/ai/src/main/java/org/yapp/infra/ai/application/ClovaChatSummarizationService.java
Labels: 기능 구현, 기능 수정, 리팩토링

#49 [PC-553] 코드 세부 수정사항 반영
  api/src/main/java/org/yapp/domain/auth/presentation/LoginController.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/request/TokenHealthCheckRequest.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchValuePickInnerResponse.java
Labels: 버그 수정, 기능 수정

#55 [PC-581] 활동지역 ENUM 추가
  api/src/main/java/org/yapp/domain/profile/enums/Location.java
Labels: 기능 구현

#57 [PC-598] 차단 연락처 동기화 시간 조회 기능 추가
  api/src/main/java/org/yapp/domain/block/application/BlockContactService.java
  api/src/main/java/org/yapp/domain/setting/application/BlockContactSyncTimeService.java
  api/src/main/java/org/yapp/domain/setting/dao/BlockContactSyncTimeRepository.java
  api/src/main/java/org/yapp/domain/setting/dto/response/BlockContactSyncTimeResponse.java
  api/src/main/java/org/yapp/domain/setting/presentation/SettingController.java
  core/domain/src/main/java/org/yapp/core/domain/setting/BlockContactSyncTime.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/BlockContactErrorCode.java
Labels: 기능 구현

#52 [PC-577] 사용자 거절 사유 조회
  admin/src/main/java/org/yapp/profile/application/AdminProfileService.java
  admin/src/main/java/org/yapp/profile/dao/ProfileRejectHistoryRepository.java
  admin/src/main/java/org/yapp/user/application/UserService.java
  admin/src/main/java/org/yapp/user/dao/UserRejectHistoryRepository.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileService.java
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/domain/user/dao/UserRejectHistoryRepository.java
  api/src/main/java/org/yapp/domain/user/presentation/UserController.java
  api/src/main/java/org/yapp/domain/user/presentation/response/UserRejectHistoryResponse.java
  core/domain/src/main/java/org/yapp/core/domain/user/UserRejectHistory.java
Labels: 기능 구현, 리팩토링

#54 [PC-580] 프로필 가치관 톡 조회 응답 형식 변경
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponse.java
  api/src/main/java/org/yapp/domain/profile/presentation/response/ProfileValueTalkResponses.java
Labels: 기능 수정

#58 [PC-175] 애플 소셜 로그인 기능
  api/build.gradle
  api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleIdTokenDecoder.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthHelper.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthProvider.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/apple/dto/AppleAuthResponse.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/auth/domain/enums/OauthType.java
  api/src/main/java/org/yapp/domain/auth/presentation/dto/request/OauthLoginRequest.java
  api/src/main/java/org/yapp/global/config/AppleOauthProperties.java
  core/domain/src/main/java/org/yapp/core/domain/auth/RefreshToken.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/AuthErrorCode.java
Labels: 기능 구현, 기능 수정

#53 [PC-579] 매칭 거절 기능 구현
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  core/domain/build.gradle
  core/domain/src/main/java/org/yapp/core/domain/match/MatchInfo.java
  core/domain/src/main/java/org/yapp/core/domain/match/enums/MatchStatus.java
  core/domain/src/main/java/org/yapp/core/domain/match/enums/UserMatchStatus.java
  core/exception/src/main/java/org/yapp/core/exception/error/code/MatchErrorCode.java
Labels: 기능 구현

#56 [PC-582] 로그아웃 기능 구현
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/LogoutService.java
  api/src/main/java/org/yapp/domain/auth/presentation/LogoutController.java
  core/auth/src/main/java/org/yapp/core/auth/token/RefreshTokenService.java
Labels: 기능 구현

#59 [PC-607] 회원 탈퇴 기능 구현
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/domain/user/presentation/UserController.java
  core/domain/src/main/java/org/yapp/core/domain/block/BlockContact.java
  core/domain/src/main/java/org/yapp/core/domain/match/MatchInfo.java
  core/domain/src/main/java/org/yapp/core/domain/report/Report.java
  core/domain/src/main/java/org/yapp/core/domain/term/TermAgreement.java
  core/domain/src/main/java/org/yapp/core/domain/user/User.java
  core/domain/src/main/java/org/yapp/core/domain/user/UserRejectHistory.java
Labels: 기능 구현

#60 [PC-611] 연락처 차단 시간 없을 때 에러 대신 시간 null으로 반환하는 것으로 변경
  api/src/main/java/org/yapp/domain/setting/application/BlockContactSyncTimeService.java
  api/src/test/java/org/yapp/domain/auth/application/dummy/TestDataService.java
  api/src/test/java/org/yapp/domain/auth/application/oauth/service/OauthServiceTest.java
Labels: 기능 수정

#61 [PC-612] 매칭 차단 정보 추가
  api/src/main/java/org/yapp/domain/block/application/DirectBlockService.java
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/request/MatchBlockRequest.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchInfoResponse.java
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkSummaryService.java
  core/domain/src/main/java/org/yapp/core/domain/match/MatchInfo.java
  core/domain/src/main/java/org/yapp/core/domain/match/enums/UserMatchStatus.java
Labels: 기능 수정

#62 [PC-615] 회원 탈퇴 이유 저장
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/domain/user/dao/UserDeleteReasonRepository.java
  api/src/main/java/org/yapp/domain/user/presentation/UserController.java
  api/src/main/java/org/yapp/domain/user/presentation/dto/request/UserDeleteRequest.java
  api/src/main/java/org/yapp/domain/user/presentation/dto/response/UserRejectHistoryResponse.java
  core/domain/src/main/java/org/yapp/core/domain/user/UserDeleteReason.java
Labels: 기능 구현

#63 [PC-623] fix: 회원가입 진행시 토큰 발급 로직 수정 (AuthTokenGenerator 사용)
  api/src/main/java/org/yapp/domain/user/application/UserService.java
Labels: 기능 수정

#65 [PC-625] 시큐리티 필터 예외 처리
  api/src/main/java/org/yapp/global/config/SecurityConfig.java
  core/auth/src/main/java/org/yapp/core/auth/jwt/JwtFilter.java
  core/auth/src/main/java/org/yapp/core/auth/jwt/JwtUtil.java
  core/exception/src/main/java/org/yapp/core/exception/GlobalExceptionHandler.java
Labels: 기능 구현, 기능 수정

#66 [PC-627] Match 관련 조회 API들에 matchedUserId 모두 추가
  api/src/main/java/org/yapp/domain/match/application/MatchService.java
  api/src/main/java/org/yapp/domain/match/presentation/MatchController.java
  api/src/main/java/org/yapp/domain/match/presentation/dto/response/MatchProfileBasicResponse.java
  api/src/main/java/org/yapp/domain/user/presentation/UserController.java
Labels: 기능 수정

#67 [PC-632] 애플 회원 탈퇴
  api/src/main/java/org/yapp/domain/auth/application/oauth/OauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/OauthProvider.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/apple/AppleOauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/google/GoogleOauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/kakao/KakaoOauthClient.java
  api/src/main/java/org/yapp/domain/auth/application/oauth/service/OauthService.java
  api/src/main/java/org/yapp/domain/user/presentation/UserController.java
  api/src/main/java/org/yapp/domain/user/presentation/dto/request/OauthUserDeleteRequest.java
  core/domain/src/main/java/org/yapp/core/domain/user/User.java
Labels: 기능 구현

#68 [PC-684] 유저 기본 정보 조회 API 추가
  api/src/main/java/org/yapp/domain/user/application/UserService.java
  api/src/main/java/org/yapp/domain/user/presentation/UserController.java
  api/src/main/java/org/yapp/domain/user/presentation/dto/response/UserBasicInfoResponse.java
Labels: 기능 구현
