Repository YAPP-Github/Piece-Server, pull requests merged in 2025-09, with the labels that each got.

#122 [PC-1136] 매칭 설정 필드 삭제
  api/src/main/java/org/yapp/domain/setting/application/SettingService.java
  api/src/main/java/org/yapp/domain/setting/dto/response/SettingInfoResponse.java
Labels: 기능 수정

#129 [PC-1249] AI 요약 전 유사도 검사
  api/build.gradle
  api/src/main/java/org/yapp/domain/profile/application/ProfileValueTalkSummaryService.java
  api/src/main/java/org/yapp/domain/profile/application/event/ProfileTalkSimilarityEventListener.java
  api/src/main/java/org/yapp/domain/profile/dao/ProfileTalkSimilarityHistoryRepository.java
  core/domain/src/main/java/org/yapp/core/domain/profile/ProfileTalkSimilarityHistory.java
  core/domain/src/main/java/org/yapp/core/domain/profile/event/ProfileTalkSimilarityAnalyzedEvent.java
  core/similarity/build.gradle
  core/similarity/src/main/java/org/yapp/core/similarity/DocumentSimilarityUtils.java
  core/similarity/src/main/java/org/yapp/core/similarity/calculator/CosineSimilarityCalculator.java
  core/similarity/src/main/java/org/yapp/core/similarity/calculator/JaccardSimilarityCalculator.java
  core/similarity/src/main/java/org/yapp/core/similarity/calculator/MultiDocumentCosineSimilarityCalculator.java
  core/similarity/src/main/java/org/yapp/core/similarity/calculator/MultiDocumentJaccardSimilarityCalculator.java
  core/similarity/src/main/java/org/yapp/core/similarity/calculator/MultiDocumentSimilarityCalculator.java
  core/similarity/src/main/java/org/yapp/core/similarity/calculator/SimilarityCalculator.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/BM25Extractor.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/FeatureExtractor.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/FeatureVector.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/MultiDocumentBM25Extractor.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/MultiDocumentFeatureExtractor.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/MultiDocumentTfIdfExtractor.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/TfExtractor.java
  core/similarity/src/main/java/org/yapp/core/similarity/feature/TfIdfExtractor.java
  core/similarity/src/main/java/org/yapp/core/similarity/pipeline/MultiDocumentSimilarityPipeline.java
  core/similarity/src/main/java/org/yapp/core/similarity/pipeline/MultiDocumentSimilarityResult.java
  core/similarity/src/main/java/org/yapp/core/similarity/pipeline/SimilarityPipeline.java
  core/similarity/src/main/java/org/yapp/core/similarity/pipeline/SimilarityResult.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/TextPreprocessor.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/cleaner/KoreanTextCleaner.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/cleaner/TextCleaner.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/remover/KoreanStopWordRemover.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/remover/StopWordRemover.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/tokenizer/KomoranTokenizer.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/tokenizer/SentenceTokenizer.java
  core/similarity/src/main/java/org/yapp/core/similarity/preprocessing/tokenizer/WhitespaceTokenizer.java
  core/similarity/src/main/java/org/yapp/core/similarity/scripts/SimilarityThresholdAnalysis.java
  core/similarity/src/test/java/org/yapp/core/similarity/calculator/CosineSimilarityCalculatorTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/calculator/JaccardSimilarityCalculatorTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/feature/BM25ExtractorTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/feature/SimilarityComparisonTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/feature/TfIdfExtractorTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/pipeline/SimilarityPipelineTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/preprocessing/StopWordRemoverTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/preprocessing/TextCleanerTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/preprocessing/TextPreprocessorTest.java
  core/similarity/src/test/java/org/yapp/core/similarity/preprocessing/TokenizerTest.java
  settings.gradle
Labels: 기능 구현, 기능 수정

#123 [PC-1155] UX writing 수정 대응 및 수동 매칭 날짜 수정
  admin/src/main/java/org/yapp/match/application/command/ManualMatchCommandService.java
  admin/src/main/java/org/yapp/notification/application/AdminNotificationService.java
  api/src/main/java/org/yapp/domain/notification/application/ApiNotificationService.java
  core/notification/src/main/java/org/yapp/core/notification/application/NotificationService.java
Labels: 버그 수정, 기능 수정

#130 [PC-1254] 나이별 가중치 적용
  api/src/main/java/org/yapp/domain/match/application/algorithm/GreedyMatchAlgorithm.java
  api/src/main/java/org/yapp/domain/match/application/algorithm/preference/AgePreferenceCalculatingPolicy.java
Labels: 기능 구현, 기능 수정
